version: '3'
services:
  mybot:
    build:
      context: "."
    image: "artifactory.zymergen.net:6556/com.zymergen/hubot:latest"
    environment:
      BIND_ADDRESS: "0.0.0.0"
      ENVIRONMENT: "development"
      SERVICE_NAME: "zed_bot"
      SERVICE_ENV: "development"
      EXPRESS_USER: "zed_bot"
      EXPRESS_PASSWORD: "zed_pw"
      PORT: "8080"
      HUBOT_ADAPTER: "slack"
      HUBOT_ALIAS: "zed"
      HUBOT_NAME: "zed_bot"
      HUBOT_LOG_LEVEL: "debug"
      REDIS_URL: "redis://redis:6379"
      HUBOT_SLACK_TOKEN: "${SLACK_TOKEN}"
      HUBOT_ASSISTANT_SECRET: "./google-assistant-secret.json"
      HUBOT_ASSISTANT_TOKEN: "./google-assistant-token.json"
      RESPOND_TO_DM: "true"
      LISTEN_ON_ALL_PUBLIC: "true"
    ports:
      - "8080:8080"
    networks:
      - my-net
  redis:
    image: "redis:3.2.5"
    expose:
      - "6379"
    networks:
      - my-net
networks:
  my-net:
    driver: bridge

