version: '2.3'
services:
  mybot:
    build:
      context: "."
    image: "${HUB_USER}/mybot:latest"
    environment:
      BIND_ADDRESS: "0.0.0.0"
      ENVIRONMENT: "development"
      SERVICE_NAME: "${STUDENT_ID}_bot"
      SERVICE_ENV: "development"
      EXPRESS_USER: "${STUDENT_ID}_bot"
      EXPRESS_PASSWORD: "${STUDENT_ID}_pw"
      PORT: "8080"
      HUBOT_ADAPTER: "${HUBOT_ADAPTER}"
      HUBOT_ALIAS: "${STUDENT_ID}"
      HUBOT_NAME: "${STUDENT_ID}_bot"
      HUBOT_LOG_LEVEL: "debug"
      REDIS_URL: "redis://redis:6379"
      HUBOT_SLACK_TOKEN: "${SLACK_TOKEN}"
      RESPOND_TO_DM: "true"
      ROCKETCHAT_URL: "${ROCKETCHAT_URL}"
      ROCKETCHAT_ROOM: ""
      LISTEN_ON_ALL_PUBLIC: "true"
      ROCKETCHAT_USER: "${ROCKETCHAT_USER}"
      ROCKETCHAT_PASSWORD: "${ROCKETCHAT_PASSWORD}"
      ROCKETCHAT_AUTH: "password"
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: "redis:3.2.5"
    expose:
      - "6379"

