version: '2.3'
services:
  rocketchat:
    image: rocketchat/rocket.chat:0.61.0
    restart: unless-stopped
    volumes:
      - "~/docker-workshop/hubot-docker/bot-with-server/rocketchat/data/uploads:/app/uploads"
    environment:
      PORT: 3000
      ROOT_URL: "http://127.0.0.1:3000"
      MONGO_URL: "mongodb://mongo:27017/rocketchat"
      MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
      MAIL_URL: "smtp://smtp.email"
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"
    networks:
      - my-net
  mongo:
    image: spkane/mongo:3.2
    restart: unless-stopped
    volumes:
     - "~/docker-workshop/hubot-docker/bot-with-server/mongodb/data/db:/data/db"
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"
    networks:
      - my-net
  mongo-init-replica:
    image: spkane/mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''127.0.0.1:27017'' } ]})"'
    depends_on:
      - mongo
    networks:
      - my-net
  mybot:
    build:
      context: ".."
    image: "${HUB_USER}/mybot:latest"
    environment:
      BIND_ADDRESS: "0.0.0.0"
      ENVIRONMENT: "development"
      SERVICE_NAME: "${STUDENT_ID}_bot"
      SERVICE_ENV: "development"
      EXPRESS_USER: "${STUDENT_ID}_bot"
      EXPRESS_PASSWORD: "${STUDENT_ID}_pw"
      PORT: "8080"
      HUBOT_ADAPTER: "rocketchat"
      HUBOT_ALIAS: "${STUDENT_ID}"
      HUBOT_NAME: "${STUDENT_ID}_bot"
      HUBOT_LOG_LEVEL: "debug"
      REDIS_URL: "redis://redis:6379"
      RESPOND_TO_DM: "true"
      ROCKETCHAT_URL: "${ROCKETCHAT_URL}"
      ROCKETCHAT_ROOM: ""
      LISTEN_ON_ALL_PUBLIC: "true"
      ROCKETCHAT_USER: "${ROCKETCHAT_USER}"
      ROCKETCHAT_PASSWORD: "${ROCKETCHAT_PASSWORD}"
      ROCKETCHAT_AUTH: "password"
    ports:
      - "8080:8080"
    depends_on:
      - rocketchat
      - redis
    networks:
      - my-net
  redis:
    image: "redis:3.2.5"
    expose:
      - "6379"
    networks:
      - my-net
networks:
  my-net:
    driver: bridge
